### ISSUE TITLE
Recipient endpoint not updated when specifying port 8081 in docker-compose

### ISSUE THREAD

**Issue by CR4YZ3R** [OpenConext/Mujina#94]
First of all thank you for the great mock!

When using this configuration in a docker-compose file
 ```
  mujina:
    image: ghcr.io/openconext/mujina/mujina-idp:sha-abedf68
    environment:
      - SERVER_PORT=8081
    ports:
      - 8081:8081
```
the following error occurs when trying to access the SSO via `http://localhost:8081/SingleSignOnService`:

`SAML message intended destination endpoint 'http://localhost:8081/SingleSignOnService' did not match the recipient endpoint 'http://localhost:8080/SingleSignOnService'`

My application uses fastapi as a backend running on port 8080. When sending the request to a fastapi endpoint `/SingleSignOnService` on port 8080 and redirecting it to localhost:8081 it however does not throw the error mentioned above. That's why I suppose that there might be an issue related to the idp mock. However I am not too familiar with this mock yet, so it might also be a silly mistake on my end ;)

Regards,
Chris
